# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
gems:                [jekyll-paginate]

# Setup
title:               Adriano Brito
tagline:             'a thinking developer'
description:         'Thoughts about my professional carrer and stuff'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Adriano Brito
  url:               https://github.com/adrianobrito
  email:             adrianosdebrito@gmail.com
  github:            https://github.com/adrianobrito
  linkedin:          https://linkedin.com

# Custom vars
version:             1.0.0
