# Site settings
title: Adriano Brito
email: adrianosdebrito@gmail.com
url: https://adrianobrito.github.io
description: "Site do Desenvolvedor de Software, Adriano Brito"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 162B2E
  secondary: FD6E8A
  secondary-dark: A2122F

# Footer settings
footer:
  copyright: Adruabi Brito
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
