# Site settings
title: Adriano Brito
email: adrianosdebrito@gmail.com
url: https://adrianobrito.github.io
description: "Site do Desenvolvedor de Software, Adriano Brito"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1B3F47 
  secondary: E95C42
  secondary-dark: 0D1D1A

# Footer settings
footer:
  copyright: Adriano Brito
  location: Home Office
  social: Contatos
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: GMail
    url: mailto
  - title: github
    url: http://github.com/adrianobrito

# Postal address (add as many lines as necessary)
address:
  - line: Rua Costa Sousa, 71, Benfica
  - line: Fortaleza, Ceará, Brasil

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
